"""Initial migration

Revision ID: 08f93a1375b4
Revises: 
Create Date: 2025-08-15 18:04:26.951052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '08f93a1375b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generations', schema=None) as batch_op:
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_ai_generations_public_id'), ['public_id'], unique=True)
        batch_op.drop_column('user_feedback')
        batch_op.drop_column('output_url')
        batch_op.drop_column('parameters')
        batch_op.drop_column('user_rating')

    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_nsfw', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('downloads_count', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_community_posts_public_id'), ['public_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_tier', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total_ai_generations', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_ai_generations', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_tokens_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_tokens_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('followers_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('following_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('posts_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes_received', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)
        batch_op.drop_column('credits_remaining')
        batch_op.drop_column('preferred_models')
        batch_op.drop_column('settings')
        batch_op.drop_column('total_generations')
        batch_op.drop_column('is_premium')
        batch_op.drop_column('tokens_used')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_used', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_premium', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('total_generations', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('settings', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preferred_models', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('credits_remaining', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_public_id'))
        batch_op.drop_column('likes_received')
        batch_op.drop_column('posts_count')
        batch_op.drop_column('following_count')
        batch_op.drop_column('followers_count')
        batch_op.drop_column('monthly_tokens_used')
        batch_op.drop_column('total_tokens_used')
        batch_op.drop_column('monthly_ai_generations')
        batch_op.drop_column('total_ai_generations')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_tier')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_posts_public_id'))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('downloads_count')
        batch_op.drop_column('is_nsfw')
        batch_op.drop_column('ai_provider')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('ai_generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_rating', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('parameters', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('output_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('user_feedback', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_ai_generations_public_id'))
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
